# Generated by Django 3.1.5 on 2021-09-09 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0001_initial'),
        ('persona', '0001_initial'),
        ('estudiante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalestudiante',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='nivel_academico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institucional.nivelacademico'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='persona',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persona.persona'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='semestre_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institucional.semestre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.nivelacademico'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programas',
            field=models.ManyToManyField(to='institucional.Programa'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='semestre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.semestre'),
        ),
    ]
