# Generated by Django 3.1.5 on 2021-02-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del banco de preguntas')),
            ],
            options={
                'verbose_name': 'Banco de preguntas',
                'verbose_name_plural': 'Bancos de preguntas',
                'ordering': ['nombre_banco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnunciadoGrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado_general', models.TextField(unique=True, verbose_name='Enunciado de la pregunta')),
            ],
            options={
                'verbose_name': 'Enunciado grupo pregunta',
                'verbose_name_plural': 'Enunciados grupo preguntas',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EnunciadoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado', models.TextField(unique=True, verbose_name='Enunciado de la pregunta')),
            ],
            options={
                'verbose_name': 'Enunciado pregunta',
                'verbose_name_plural': 'Enunciados pregunta',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('cantidad_preguntas', models.PositiveSmallIntegerField(unique=True, verbose_name='Cantidad maxíma de preguntas')),
            ],
            options={
                'verbose_name': 'Grupo de preguntas',
                'verbose_name_plural': 'Grupos de pregusntas',
                'ordering': ['cantidad_preguntas'],
            },
        ),
        migrations.CreateModel(
            name='HojaRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('tiempo_empleado', models.TimeField(verbose_name='Tiempo que empleo para responder la pregunta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('grupo_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta')),
            ],
            options={
                'verbose_name': 'Hoja de respuesta',
                'verbose_name_plural': 'Hoja de respuestas',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('afirmacion', models.CharField(max_length=250, verbose_name='Afirmación')),
                ('evidencia', models.CharField(max_length=250, verbose_name='Evidencia')),
                ('justificacion', models.TextField(verbose_name='Justificacion de la pregunta')),
            ],
            options={
                'verbose_name': 'Justificacion',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('codigo_modulo', models.CharField(max_length=50, verbose_name='Código del módulo')),
                ('nombre_modulo', models.CharField(max_length=100, verbose_name='Nombre del módulo')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre_modulo'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEnunciado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('contenido_opcion', models.CharField(max_length=250, unique=True, verbose_name='Contenido de la opción')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P')], max_length=1, unique=True, verbose_name='Letra')),
            ],
            options={
                'verbose_name': 'Opcion Enunciado',
                'verbose_name_plural': 'Opciones enunciado',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('letra_opcion', models.CharField(max_length=1, unique=True, verbose_name='nombre de la opcion')),
            ],
            options={
                'verbose_name': 'Opcion respuesta',
                'verbose_name_plural': 'Opciones respuesta',
                'ordering': ['letra_opcion'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_prueba', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la prueba')),
                ('limite_tiempo', models.TimeField(verbose_name='Limite de tiempo para presentar la prueba')),
                ('numero_intentos', models.PositiveSmallIntegerField(default=1)),
                ('banco_preguntas', models.ManyToManyField(to='prueba.BancoPreguntas')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['nombre_prueba'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('calificacion', models.BooleanField(default=False, verbose_name='Calificación de la prueba')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('hoja_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.hojarespuesta')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.prueba')),
            ],
            options={
                'verbose_name': 'Resultado de la prueba',
                'verbose_name_plural': 'Resultados de las pruebas',
                'ordering': ['estudiante'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta')),
                ('justificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.justificacion')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionenunciado')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='justificacion',
            name='solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta'),
        ),
        migrations.CreateModel(
            name='ImagenEnunciadoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('imagen_enunciado', models.ImageField(max_length=200, upload_to=None, verbose_name='Imagen pregunta')),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.enunciadopregunta')),
            ],
            options={
                'verbose_name': 'Imagen para pregunta',
                'verbose_name_plural': 'Imagenes para preguntas',
            },
        ),
        migrations.CreateModel(
            name='ImagenEnunciadoGrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('imagen', models.ImageField(max_length=200, upload_to=None, verbose_name='Imagen grupo preguntas')),
                ('enunciado_grupo_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.enunciadogrupopregunta')),
            ],
            options={
                'verbose_name': 'Imagen para grupo de preguntas',
                'verbose_name_plural': 'Imagenes para grupo de preguntas',
            },
        ),
        migrations.AddField(
            model_name='hojarespuesta',
            name='opcion_marcada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='hojarespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='hojarespuesta',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.prueba'),
        ),
        migrations.AddField(
            model_name='enunciadopregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='enunciadogrupopregunta',
            name='grupo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_competencia', models.CharField(max_length=100, verbose_name='Nombre de la competencia')),
                ('porcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de la competencia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['nombre_competencia'],
            },
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='competencia',
            field=models.ManyToManyField(to='prueba.Competencia'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='grupo_pregunta',
            field=models.ManyToManyField(to='prueba.GrupoPregunta'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='pregunta',
            field=models.ManyToManyField(to='prueba.Pregunta'),
        ),
    ]
