# Generated by Django 3.1.5 on 2021-01-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado_general', models.TextField(verbose_name='Nombre del grupo de preguntas')),
                ('cantidad_max_pregutas', models.IntegerField(unique=True, verbose_name='Cantidad maxíma de preguntas')),
            ],
            options={
                'verbose_name': 'GrupoPregunta',
                'verbose_name_plural': 'GrupoPregusntas',
                'ordering': ['enunciado_general'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('afirmacion', models.CharField(max_length=250, verbose_name='Afirmación')),
                ('evidencia', models.CharField(max_length=250, verbose_name='Evidencia')),
                ('justificacion', models.TextField(verbose_name='Justificacion de la pregunta')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('codigo_modulo', models.CharField(max_length=50, verbose_name='Código del módulo')),
                ('nombre_modulo', models.CharField(max_length=100, verbose_name='Nombre del módulo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del módulo')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre_modulo'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEnunciado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('contenido_opcion', models.CharField(max_length=250, unique=True, verbose_name='Contenido de la opción')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=1, unique=True, verbose_name='Letra')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('letra_opcion', models.CharField(max_length=1, unique=True, verbose_name='nombre de la opcion')),
            ],
            options={
                'verbose_name': 'OpcionRespuesta',
                'verbose_name_plural': 'OpcionesRespuesta',
                'ordering': ['letra_opcion'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado', models.TextField(unique=True, verbose_name='Enunciado de la pregunta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta')),
                ('justificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.justificacion')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionenunciado')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='justificacion',
            name='solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_competencia', models.CharField(max_length=100, verbose_name='Nombre de la competencia')),
                ('porcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de la competencia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['nombre_competencia'],
            },
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del banco de preguntas')),
                ('competencia', models.ManyToManyField(to='prueba.Competencia')),
                ('grupo', models.ManyToManyField(to='prueba.GrupoPregunta')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
                ('pregunta', models.ManyToManyField(to='prueba.Pregunta')),
            ],
            options={
                'verbose_name': 'BancoPregunta',
                'verbose_name_plural': 'BancoPreguntas',
                'ordering': ['nombre_banco'],
                'managed': True,
            },
        ),
    ]
