# Generated by Django 3.1.5 on 2021-07-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0002_auto_20210314_0410'),
        ('estudiante', '0002_auto_20210314_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del banco de preguntas')),
            ],
            options={
                'verbose_name': 'Banco de preguntas',
                'verbose_name_plural': 'Bancos de preguntas',
                'ordering': ['nombre_banco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnunciadoGrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado_general', models.TextField(unique=True, verbose_name='Enunciado general del grupo de preguntas')),
            ],
            options={
                'verbose_name': 'Enunciado grupo pregunta',
                'verbose_name_plural': 'Enunciados grupo preguntas',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EnunciadoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('enunciado', models.TextField(unique=True, verbose_name='Enunciado de la pregunta')),
            ],
            options={
                'verbose_name': 'Enunciado pregunta',
                'verbose_name_plural': 'Enunciados pregunta',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_grupo', models.CharField(max_length=200, verbose_name='Nombre del grupo')),
                ('cantidad_preguntas', models.PositiveSmallIntegerField(verbose_name='Cantidad maxíma de preguntas')),
                ('banco_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.bancopreguntas')),
            ],
            options={
                'verbose_name': 'Grupo de preguntas',
                'verbose_name_plural': 'Grupos de pregusntas',
                'ordering': ['nombre_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('afirmacion', models.CharField(max_length=250, verbose_name='Afirmación')),
                ('evidencia', models.CharField(max_length=250, verbose_name='Evidencia')),
                ('justificacion', models.TextField(verbose_name='Justificacion de la pregunta')),
            ],
            options={
                'verbose_name': 'Justificacion',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_modulo', models.CharField(max_length=100, verbose_name='Nombre del módulo')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre_modulo'],
            },
        ),
        migrations.CreateModel(
            name='NivelDificultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel de dificultad')),
            ],
            options={
                'verbose_name': 'Nivel de dificultad pregunta',
                'verbose_name_plural': 'Niveles de dificultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NivelEjecucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel de desempeño')),
                ('puntaje_minimo', models.PositiveSmallIntegerField(verbose_name='Puntaje minimo')),
                ('puntaje_maximo', models.PositiveSmallIntegerField(verbose_name='Puntaje maximo')),
                ('descripcion_general', models.TextField(verbose_name='Descripción nivel')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
            ],
            options={
                'verbose_name': 'Nivel de desempeño',
                'verbose_name_plural': 'Niveles de desempeño',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('letra_opcion', models.CharField(max_length=1, unique=True, verbose_name='nombre de la letra')),
            ],
            options={
                'verbose_name': 'Opcion respuesta',
                'verbose_name_plural': 'Opciones respuesta',
                'ordering': ['letra_opcion'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_prueba', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la prueba')),
                ('limite_tiempo', models.TimeField(verbose_name='Limite de tiempo para presentar la prueba')),
                ('numero_intentos', models.PositiveSmallIntegerField(default=1)),
                ('banco_preguntas', models.ManyToManyField(to='prueba.BancoPreguntas')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['nombre_prueba'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PruebasEstudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('presentada', models.BooleanField(default=False, verbose_name='Prueba presentada')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.prueba')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('calificada', models.BooleanField(default=False, verbose_name='Prueba calificada')),
                ('numero_aciertos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respuestas correctas')),
                ('numero_desaciertos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respuestas incorrectas')),
                ('tiempo_empleado', models.TimeField(verbose_name='Tiempo empleado en la prueba')),
                ('calificacion_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.nivelejecucion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
                ('prueba_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pruebasestudiante')),
            ],
            options={
                'verbose_name': 'Resultado de la prueba',
                'verbose_name_plural': 'Resultados de las pruebas',
                'ordering': ['prueba_asignada', 'estudiante'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('banco_preguntas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.bancopreguntas')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta')),
                ('justificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.justificacion')),
                ('nivel_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.niveldificultad')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('contenido_opcion', models.CharField(max_length=250, unique=True, verbose_name='Contenido de la opción')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P')], max_length=1, verbose_name='Letra')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta')),
            ],
            options={
                'verbose_name': 'Opcion Enunciado',
                'verbose_name_plural': 'Opciones enunciado',
            },
        ),
        migrations.CreateModel(
            name='ImagenEnunciadoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('imagen_enunciado', models.ImageField(max_length=200, upload_to=None, verbose_name='Imagen pregunta')),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.enunciadopregunta')),
            ],
            options={
                'verbose_name': 'Imagen para pregunta',
                'verbose_name_plural': 'Imagenes para preguntas',
            },
        ),
        migrations.CreateModel(
            name='ImagenEnunciadoGrupoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('imagen', models.ImageField(max_length=200, upload_to=None, verbose_name='Imagen grupo preguntas')),
                ('enunciado_grupo_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.enunciadogrupopregunta')),
            ],
            options={
                'verbose_name': 'Imagen para grupo de preguntas',
                'verbose_name_plural': 'Imagenes para grupo de preguntas',
            },
        ),
        migrations.CreateModel(
            name='HojaRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('tiempo_empleado_pregunta', models.TimeField(verbose_name='Tiempo que empleo para responder la pregunta')),
                ('calificacion', models.BooleanField(default=False, verbose_name='Calificación pregunta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('opcion_marcada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta')),
                ('prueba_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pruebasestudiante')),
            ],
            options={
                'verbose_name': 'Hoja de respuesta',
                'verbose_name_plural': 'Hoja de respuestas',
            },
        ),
        migrations.AddField(
            model_name='enunciadopregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='enunciadogrupopregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta'),
        ),
        migrations.CreateModel(
            name='DescripcionNivelEjecucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('descripcion_especifica', models.TextField(verbose_name='Descripción especifica nivel desempeño')),
                ('nivel_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.nivelejecucion')),
            ],
            options={
                'verbose_name': 'Descripcion especifica nivel de desempeño',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nombre_competencia', models.CharField(max_length=100, verbose_name='Nombre de la competencia')),
                ('porcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de la competencia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['nombre_competencia'],
            },
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='competencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.competencia'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo'),
        ),
    ]
