# Generated by Django 3.1.5 on 2021-09-09 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0002_auto_20210909_0310'),
        ('prueba', '0001_initial'),
        ('estudiante', '0002_auto_20210909_0310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresultadoprueba',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresultadoprueba',
            name='modulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='historicalresultadoprueba',
            name='prueba_asignada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.pruebasestudiante'),
        ),
        migrations.AddField(
            model_name='historicalpruebasestudiante',
            name='estudiante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estudiante.estudiante'),
        ),
        migrations.AddField(
            model_name='historicalpruebasestudiante',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpruebasestudiante',
            name='prueba',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.prueba'),
        ),
        migrations.AddField(
            model_name='historicalprueba',
            name='docente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docente.docente'),
        ),
        migrations.AddField(
            model_name='historicalprueba',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='banco_preguntas',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.bancopreguntas'),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.grupopregunta'),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='justificacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.justificacion'),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='nivel_dificultad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.niveldificultad'),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='respuesta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='historicalopcionrespuesta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalopcionpregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalopcionpregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='historicalnivelejecucion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnivelejecucion',
            name='modulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='historicalniveldificultad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmodulo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljustificacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimagenenunciadopregunta',
            name='enunciado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.enunciadopregunta'),
        ),
        migrations.AddField(
            model_name='historicalimagenenunciadopregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimagenenunciadogrupopregunta',
            name='enunciado_grupo_preguntas',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.enunciadogrupopregunta'),
        ),
        migrations.AddField(
            model_name='historicalimagenenunciadogrupopregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhojarespuesta',
            name='estudiante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estudiante.estudiante'),
        ),
        migrations.AddField(
            model_name='historicalhojarespuesta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhojarespuesta',
            name='opcion_marcada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='historicalhojarespuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='historicalhojarespuesta',
            name='prueba_asignada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.pruebasestudiante'),
        ),
        migrations.AddField(
            model_name='historicalgrupopregunta',
            name='banco_preguntas',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.bancopreguntas'),
        ),
        migrations.AddField(
            model_name='historicalgrupopregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenunciadopregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenunciadopregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='historicalenunciadogrupopregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.grupopregunta'),
        ),
        migrations.AddField(
            model_name='historicalenunciadogrupopregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldescripcionnivelejecucion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldescripcionnivelejecucion',
            name='nivel_ejecucion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.nivelejecucion'),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='modulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='historicalbancopreguntas',
            name='competencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.competencia'),
        ),
        migrations.AddField(
            model_name='historicalbancopreguntas',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbancopreguntas',
            name='modulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='grupopregunta',
            name='banco_preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.bancopreguntas'),
        ),
        migrations.AddField(
            model_name='enunciadopregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AddField(
            model_name='enunciadogrupopregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta'),
        ),
        migrations.AddField(
            model_name='descripcionnivelejecucion',
            name='nivel_ejecucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.nivelejecucion'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='competencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.competencia'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.modulo'),
        ),
    ]
