# Generated by Django 3.1.5 on 2021-09-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nombre_competencia',
            field=models.CharField(max_length=250, verbose_name='Nombre de la competencia'),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='nombre_competencia',
            field=models.CharField(max_length=250, verbose_name='Nombre de la competencia'),
        ),
    ]
