# Generated by Django 3.1.5 on 2021-10-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20210909_0310'),
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopreguntas',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.docente'),
        ),
        migrations.AlterField(
            model_name='grupopregunta',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.docente'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.docente'),
        ),
    ]
