# Generated by Django 3.1.5 on 2021-09-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopreguntas',
            name='nombre_banco',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del banco de preguntas'),
        ),
        migrations.AlterField(
            model_name='historicalbancopreguntas',
            name='nombre_banco',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre del banco de preguntas'),
        ),
    ]
