# Generated by Django 3.1.5 on 2021-07-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='calificada',
            field=models.BooleanField(default=False, verbose_name='Prueba calificada'),
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='numero_aciertos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respuestas correctas'),
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='numero_desaciertos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respuestas incorrectas'),
        ),
    ]
