# Generated by Django 3.1.5 on 2021-02-23 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopreguntas',
            name='grupo_pregunta',
            field=models.ManyToManyField(blank=True, null=True, to='prueba.GrupoPregunta'),
        ),
        migrations.AlterField(
            model_name='bancopreguntas',
            name='pregunta',
            field=models.ManyToManyField(blank=True, null=True, to='prueba.Pregunta'),
        ),
        migrations.AlterField(
            model_name='hojarespuesta',
            name='grupo_preguntas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta'),
        ),
        migrations.AlterField(
            model_name='hojarespuesta',
            name='opcion_marcada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.opcionrespuesta'),
        ),
        migrations.AlterField(
            model_name='hojarespuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.grupopregunta'),
        ),
    ]
