# Generated by Django 3.1.5 on 2021-03-19 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_remove_justificacion_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadopregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.pregunta'),
        ),
    ]
