# Generated by Django 3.1.5 on 2021-02-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20210223_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopreguntas',
            name='grupo_pregunta',
            field=models.ManyToManyField(to='prueba.GrupoPregunta'),
        ),
    ]
