# Generated by Django 3.1.5 on 2021-09-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20210929_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nombre_competencia',
            field=models.TextField(verbose_name='Nombre de la competencia'),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='nombre_competencia',
            field=models.TextField(verbose_name='Nombre de la competencia'),
        ),
    ]
