# Generated by Django 3.1.5 on 2021-07-12 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20210712_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojarespuesta',
            old_name='tiempo_empleado',
            new_name='tiempo_empleado_pregunta',
        ),
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='hoja_respuesta',
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='tiempo_empleado',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Tiempo empleado en la prueba'),
            preserve_default=False,
        ),
    ]
