# Generated by Django 3.1.5 on 2021-03-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20210319_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionpregunta',
            name='letra',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P')], max_length=1, verbose_name='Letra'),
        ),
    ]
