# Generated by Django 3.1.5 on 2021-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20210224_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopreguntas',
            name='pregunta',
            field=models.ManyToManyField(to='prueba.Pregunta'),
        ),
    ]
