# Generated by Django 3.1.5 on 2021-03-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_auto_20210319_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enunciadogrupopregunta',
            old_name='grupo_pregunta',
            new_name='grupo',
        ),
    ]
