# Generated by Django 3.1.5 on 2021-01-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.nivelacademico')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
