# Generated by Django 3.1.5 on 2021-02-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('identificacion', models.PositiveSmallIntegerField(unique=True, verbose_name='Número de identificación')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('genero', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('LGTIB', 'LGTIB')], max_length=6, verbose_name='Genéro')),
                ('rh', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguineo')),
                ('estado_civil', models.CharField(max_length=15, verbose_name='Estado civil')),
                ('telefono', models.PositiveSmallIntegerField(unique=True, verbose_name='Número de télefono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido'],
            },
        ),
    ]
