# Generated by Django 3.1.5 on 2021-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO'), ('DIVORCIADO', 'DIVORCIADO(A)'), ('VIUDO', 'VIUDO(A)'), ('UNION_LIBRE', 'UNION_LIBRE')], max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de télefono'),
        ),
    ]
