# Generated by Django 3.1.5 on 2021-03-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210301_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de télefono'),
        ),
    ]
