# Generated by Django 3.1.5 on 2021-03-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('codigo_facultad', models.CharField(max_length=50, unique=True, verbose_name='Código de la facultad')),
                ('nombre_facultad', models.CharField(max_length=100, verbose_name='Nombre de la facultad')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre_facultad'],
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('nivel_academico', models.CharField(max_length=50, unique=True, verbose_name='Nivel académico')),
            ],
            options={
                'verbose_name': 'Nivel academico',
                'verbose_name_plural': 'Niveles académicos',
                'ordering': ['nivel_academico'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha deeliminación')),
                ('codigo_programa', models.CharField(max_length=50, unique=True, verbose_name='Código del programa')),
                ('nombre_programa', models.CharField(max_length=100, unique=True, verbose_name='Nombre del programa')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='Creditos academicos del programa')),
                ('semestres', models.PositiveSmallIntegerField(verbose_name='Semetres')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.facultad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre_programa'],
            },
        ),
    ]
