# Generated by Django 3.1.5 on 2021-07-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='codigo_programa',
        ),
    ]
