# Generated by Django 3.1.5 on 2021-08-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_remove_programa_codigo_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='codigo_facultad',
        ),
    ]
